### ISSUE TITLE
AWS/GCP: scylla-image-setup.service fails when no additional SSDs for RAID added on the instance

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla-machine-image#111]
Seems like we have a bug to handle RAID for gcp, when no free disks available.
On the instance which added additional SSDs just works finely, so problem is no disk case.
Correct behavior for this is, detect no additional disks and skip RAID setup.

```
last failed login: Tue Mar 23 13:33:23 UTC 2021 from 35.235.240.66 on ssh:notty
There was 1 failed login attempt since the last successful login.

   _____            _ _       _____  ____  
  / ____|          | | |     |  __ \|  _ \ 
 | (___   ___ _   _| | | __ _| |  | | |_) |
  \___ \ / __| | | | | |/ _` | |  | |  _ < 
  ____) | (__| |_| | | | (_| | |__| | |_) |
 |_____/ \___|\__, |_|_|\__,_|_____/|____/ 
               __/ |                       
              |___/                        

Version:
       4.4.dev-0.20201208.f802356572
Nodetool:
        nodetool help
CQL Shell:
        cqlsh
More documentation available at: 
        http://www.scylladb.com/doc/
By default, Scylla sends certain information about this node to a data collection server. For information, see http://www.scylladb.com/privacy/

    Initial image configuration failed!

To see status, run 
 'systemctl status scylla-image-setup'

[syuu@takuya-scylla-test1 ~]$ systemctl status scylla-image-setup --no-pager -l
● scylla-image-setup.service - Scylla Cloud Image Setup service
   Loaded: loaded (/usr/lib/systemd/system/scylla-image-setup.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2021-03-23 13:33:25 UTC; 1min 17s ago
  Process: 943 ExecStart=/opt/scylladb/scylla-machine-image/scylla_image_setup (code=exited, status=1/FAILURE)
 Main PID: 943 (code=exited, status=1/FAILURE)

Mar 23 13:33:25 takuya-scylla-test1 scylla_image_setup[943]: AssertionError: No NVMe devices found!
Mar 23 13:33:25 takuya-scylla-test1 scylla_image_setup[943]: Traceback (most recent call last):
Mar 23 13:33:25 takuya-scylla-test1 scylla_image_setup[943]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_image_setup", line 27, in <module>
Mar 23 13:33:25 takuya-scylla-test1 scylla_image_setup[943]:     run('/opt/scylladb/scylla-machine-image/scylla_create_devices', shell=True, check=True)
Mar 23 13:33:25 takuya-scylla-test1 scylla_image_setup[943]:   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
Mar 23 13:33:25 takuya-scylla-test1 scylla_image_setup[943]:     raise CalledProcessError(retcode, process.args,
Mar 23 13:33:25 takuya-scylla-test1 scylla_image_setup[943]: subprocess.CalledProcessError: Command '/opt/scylladb/scylla-machine-image/scylla_create_devices' returned non-zero exit status 1.
Mar 23 13:33:25 takuya-scylla-test1 systemd[1]: scylla-image-setup.service: Main process exited, code=exited, status=1/FAILURE
Mar 23 13:33:25 takuya-scylla-test1 systemd[1]: scylla-image-setup.service: Failed with result 'exit-code'.
Mar 23 13:33:25 takuya-scylla-test1 systemd[1]: Failed to start Scylla Cloud Image Setup service.

[syuu@takuya-scylla-test1 ~]$ sudo /opt/scylladb/scylla-machine-image/scylla_create_devices 
ls: cannot access '/dev/nvme0n*': No such file or directory
Traceback (most recent call last):
  File "/opt/scylladb/scylla-machine-image/libexec/scylla_create_devices", line 218, in <module>
    nvme_devices = get_nvme_devices()
  File "/opt/scylladb/scylla-machine-image/libexec/scylla_create_devices", line 195, in get_nvme_devices
    assert devices, "No NVMe devices found!"
AssertionError: No NVMe devices found!
```

**Comment by syuu1228** [comment]
"Forgetting to add" may misleading title, since without addtional SSDs is still valid configuration for Scylla, so renamed the title.

**Comment by syuu1228** [comment]
Found that it also may occur on AWS.
But unlike on GCE, we always force to create maximum number of ephemeral disks, so this never happen on supported instance (because all supported instance has ephemeral).
However, some unsupported instances does not have ephemeral disks, we may get same error on AWS too: 

```
Mar 23 17:01:03 ip-10-0-0-174 scylla_image_setup[1061]: Traceback (most recent call last):
Mar 23 17:01:03 ip-10-0-0-174 scylla_image_setup[1061]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_create_devices", line 76, in <module>
Mar 23 17:01:03 ip-10-0-0-174 scylla_image_setup[1061]:     create_raid(disk_devices)
Mar 23 17:01:03 ip-10-0-0-174 scylla_image_setup[1061]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_create_devices", line 33, in create_raid
Mar 23 17:01:03 ip-10-0-0-174 scylla_image_setup[1061]:     run(["/opt/scylladb/scripts/scylla_raid_setup", "--disks", ",".join(devices),
Mar 23 17:01:03 ip-10-0-0-174 scylla_image_setup[1061]:   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
Mar 23 17:01:03 ip-10-0-0-174 scylla_image_setup[1061]:     raise CalledProcessError(retcode, process.args,
Mar 23 17:01:03 ip-10-0-0-174 scylla_image_setup[1061]: subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_raid_setup', '--disks', '', '--root', '/var/lib/scylla', '--volume-role', 'all', '--update-fstab']' returned non-zero exit status 1.
Mar 23 17:01:03 ip-10-0-0-174 scylla_image_setup[1049]: 2021-03-23 17:01:03,321 - [scylla_configure] - ERROR - Failed to create devices: Command '/opt/scylladb/scylla-machine-image/scylla_create_devices ' returned non-zero exit status 1.
Mar 23 17:01:03 ip-10-0-0-174 scylla_image_setup[1049]: Failed to create devices: Command '/opt/scylladb/scylla-machine-image/scylla_create_devices ' returned non-zero exit status 1.
Mar 23 17:01:03 ip-10-0-0-174 scylla_image_setup[1029]: Traceback (most recent call last):
Mar 23 17:01:03 ip-10-0-0-174 scylla_image_setup[1029]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_image_setup", line 26, in <module>
Mar 23 17:01:03 ip-10-0-0-174 scylla_image_setup[1029]:     run('/opt/scylladb/scylla-machine-image/scylla_configure.py', shell=True, check=True)
Mar 23 17:01:03 ip-10-0-0-174 scylla_image_setup[1029]:   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
Mar 23 17:01:03 ip-10-0-0-174 scylla_image_setup[1029]:     raise CalledProcessError(retcode, process.args,
Mar 23 17:01:03 ip-10-0-0-174 scylla_image_setup[1029]: subprocess.CalledProcessError: Command '/opt/scylladb/scylla-machine-image/scylla_configure.py' returned non-zero exit status 1.
Mar 23 17:01:03 ip-10-0-0-174 systemd[1]: scylla-image-setup.service: Main process exited, code=exited, status=1/FAILURE
-- An ExecStart= process belonging to unit scylla-image-setup.service has exited.
Mar 23 17:01:03 ip-10-0-0-174 systemd[1]: scylla-image-setup.service: Failed with result 'exit-code'.
-- The unit scylla-image-setup.service has entered the 'failed' state with result 'exit-code'.
```

**Comment by syuu1228** [comment]
Probably failing scylla-image-setup.service is correct since we need RAID volume, but it should not with python traceback, should be human readable error message.
