### ISSUE TITLE
Failed to build machine-image deb package

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-machine-image#114]
This happens  in enterprise but should be fixed here and then backport 
in https://jenkins.scylladb.com/view/nexts/job/scylla-enterprise/job/unified-deb/181/consoleFull we got the following error:

```
16:10:21  Traceback (most recent call last):
16:10:21    File "/usr/lib64/python3.9/shutil.py", line 806, in move
16:10:21      os.rename(src, real_dst)
16:10:21  FileNotFoundError: [Errno 2] No such file or directory: 'build/debian/scylla-machine-image/debian/scylla-image-setup.service' -> 'build/debian/scylla-enterprise-machine-image/debian/scylla-enterprise-image-setup.service'
16:10:21  
16:10:21  During handling of the above exception, another exception occurred:
16:10:21  
16:10:21  Traceback (most recent call last):
16:10:21    File "/jenkins/workspace/scylla-enterprise/unified-deb/scylla-machine-image/./dist/debian/debian_files_gen.py", line 55, in <module>
16:10:21      shutil.move(p, p.replace('scylla-', '{}-'.format(product)))
16:10:21    File "/usr/lib64/python3.9/shutil.py", line 820, in move
16:10:21      copy_function(src, real_dst)
16:10:21    File "/usr/lib64/python3.9/shutil.py", line 435, in copy2
16:10:21      copyfile(src, dst, follow_symlinks=follow_symlinks)
16:10:21    File "/usr/lib64/python3.9/shutil.py", line 264, in copyfile
16:10:21      with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
16:10:21  FileNotFoundError: [Errno 2] No such file or directory: 'build/debian/scylla-enterprise-machine-image/debian/scylla-enterprise-image-setup.service'
```

**Comment by yaronkaikov** [comment]
@syuu1228  it looks like we are expecting the service name to be `scylla-enterprise` while it's always `scylla` 

Can you please have a look?

**Comment by syuu1228** [comment]
Isn't it same issue with https://github.com/scylladb/scylla-enterprise-machine-image/issues/16?
Seems like the fix https://github.com/scylladb/scylla-machine-image/pull/113 is not yet merged

**Comment by yaronkaikov** [comment]
@syuu1228 Yes it is.closing as it's duplicate
