### ISSUE TITLE
scylla-image-post-start.service fails when userdata is not specified

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla-machine-image#270]
Looks like scylla-image-post-start.service fails when userdata is not specified.
This won't break scylla-server.service since the service start after scylla-server, but better to fix.

```
Dec 20 06:56:50 ip-10-0-17-230 scylla_post_start.py[7434]: 2021-12-20 06:56:50,982 - [scylla_post_start] - WARNING - Error getting user data: HTTP Error 404: Not Found
Dec 20 06:56:50 ip-10-0-17-230 scylla_post_start.py[7434]: Error getting user data: HTTP Error 404: Not Found
Dec 20 06:56:50 ip-10-0-17-230 scylla_post_start.py[7434]: Traceback (most recent call last):
Dec 20 06:56:50 ip-10-0-17-230 scylla_post_start.py[7434]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_post_start.py", line 71, in <module>
Dec 20 06:56:50 ip-10-0-17-230 scylla_post_start.py[7434]:     if init.run_post_start_script():
Dec 20 06:56:50 ip-10-0-17-230 scylla_post_start.py[7434]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_post_start.py", line 57, in run_post_start_script
Dec 20 06:56:50 ip-10-0-17-230 scylla_post_start.py[7434]:     post_start_script = self.instance_user_data.get("post_start_script")
Dec 20 06:56:50 ip-10-0-17-230 scylla_post_start.py[7434]: AttributeError: 'NoneType' object has no attribute 'get'
Dec 20 06:56:50 ip-10-0-17-230 systemd[1]: scylla-image-post-start.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by syuu1228** [comment]
@benipeled I'm not sure the error still happens on latest master but at least still happens on enterprise-2022 and 5.0 (#375), any idea with this?

**Comment by benipeled** [comment]
@syuu1228 as part of https://github.com/scylladb/scylla-machine-image/pull/379#issuecomment-1195281577, I checked both 5.0 and 2022.1 without userdata and didn't face this issue,
I'm not sure what fixed it but unless I missed something it's no longer reproducible

**Comment by fruch** [comment]
@syuu1228 I think I'm fixing it in:
https://github.com/scylladb/scylla-machine-image/pull/378

**Comment by yaronkaikov** [comment]
Closed via https://github.com/scylladb/scylla-machine-image/pull/378
