### ISSUE TITLE
AWS - Scylla Version 4.5.3 AMI fails during scylla-image-setup.service

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylla-machine-image#311]
**AMI**: `ami-0c6e0369e5fcb5564`
**Region/AZ**: `us-east-1a`
**Number of nodes**: 3
**InstanceType**: i3.2xlarge

**Description**:
Scylla 4.5.3 AMI fails within `scylla-image-setup.service` with `Failed to receive 1 resource signal(s) within the specified duration`.

![image](https://user-images.githubusercontent.com/82817126/155189745-37e346c9-519a-49e5-bba6-494ca5e47660.png)

It turns out that during the bootstrap we are calling `yum -y install` to set-up aws-cfn, but we are using Ubuntu as a base image:
```
scyllaadm@ip-172-31-0-11:~$ sudo systemctl status scylla-image-setup -l --no-pager
● scylla-image-setup.service - Scylla Cloud Image Setup service
     Loaded: loaded (/lib/systemd/system/scylla-image-setup.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-02-22 16:53:28 UTC; 4min 37s ago
   Main PID: 585 (code=exited, status=1/FAILURE)

Feb 22 16:53:28 ip-172-31-0-11 scylla_image_setup[902]: Post configuration script failed: Command 'b'#!/bin/bash -ex\n\nsudo yum -y install epel-release\nsudo yum -y install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.amzn1.noarch.rpm\nln -s /usr/local/lib/python2.7/site-packages/cfnbootstrap /usr/lib/python2.7/site-packages/cfnbootstrap\n/opt/aws/bin/cfn-signal --exit-code 0 --resource Node0 --region us-east-1 --stack scylla-handsome-oss\n'' returned non-zero exit status 127.
Feb 22 16:53:28 ip-172-31-0-11 scylla_image_setup[585]: Traceback (most recent call last):
Feb 22 16:53:28 ip-172-31-0-11 scylla_image_setup[585]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_image_setup", line 29, in <module>
Feb 22 16:53:28 ip-172-31-0-11 scylla_image_setup[585]:     run('/opt/scylladb/scylla-machine-image/scylla_configure.py', shell=True, check=True)
Feb 22 16:53:28 ip-172-31-0-11 scylla_image_setup[585]:   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
Feb 22 16:53:28 ip-172-31-0-11 scylla_image_setup[585]:     raise CalledProcessError(retcode, process.args,
Feb 22 16:53:28 ip-172-31-0-11 scylla_image_setup[585]: subprocess.CalledProcessError: Command '/opt/scylladb/scylla-machine-image/scylla_configure.py' returned non-zero exit status 1.
Feb 22 16:53:28 ip-172-31-0-11 systemd[1]: scylla-image-setup.service: Main process exited, code=exited, status=1/FAILURE
Feb 22 16:53:28 ip-172-31-0-11 systemd[1]: scylla-image-setup.service: Failed with result 'exit-code'.
Feb 22 16:53:28 ip-172-31-0-11 systemd[1]: Failed to start Scylla Cloud Image Setup service.
```

**Comment by yaronkaikov** [comment]
@fee-mendes How did you create this cluster? did you use our template  from Scylla website?

**Comment by fee-mendes** [comment]
> @fee-mendes How did you create this cluster? did you use our template from Scylla website?

Yes

**Comment by yaronkaikov** [comment]
@fee-mendes , found the problem, it will be fixed as part of 4.5.5 (currently we are about to promote 4.5.4 , so i will have to fix it manually)

**Comment by fee-mendes** [comment]
Thanks @yaronkaikov ! Very appreciated <3

**Comment by yaronkaikov** [comment]
@benipeled I assume we are missing some backport for cloudformation in 4.5, can you please find those missing commits, and let's fix cloudformation for 4.5

**Comment by benipeled** [comment]
We have many changes added to 4.6+ around arm and cluster default password,
I'll create a specific patch to fix this package mess on 4.5

**Comment by yaronkaikov** [comment]
fixed in https://github.com/scylladb/scylla-machine-image/pull/313
