### ISSUE TITLE
Error in post_start_script.py on Azure

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-machine-image#353]
I've been looking at logs when testing Scylla on Azure and got into such error:
```
< t:2022-05-06 19:56:43,308 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-06T17:56:42+00:00 longevity-mini-test-ls-db-node-eastus-2 !    INFO | 2022-05-06 17:56:42,931 - [scylla_post_start] - WARNING - Error getting user data: 'azure_instance' object has no attribute 'user_data'
< t:2022-05-06 19:56:43,308 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-06T17:56:42+00:00 longevity-mini-test-ls-db-node-eastus-2 !    INFO | Error getting user data: 'azure_instance' object has no attribute 'user_data'
< t:2022-05-06 19:56:43,308 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-06T17:56:42+00:00 longevity-mini-test-ls-db-node-eastus-2 !    INFO | Traceback (most recent call last):
< t:2022-05-06 19:56:43,308 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-06T17:56:42+00:00 longevity-mini-test-ls-db-node-eastus-2 !    INFO |   File "/opt/scylladb/scylla-machine-image/libexec/scylla_post_start.py", line 71, in <module>
< t:2022-05-06 19:56:43,308 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-06T17:56:42+00:00 longevity-mini-test-ls-db-node-eastus-2 !    INFO |     if init.run_post_start_script():
< t:2022-05-06 19:56:43,409 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 022-05-06T17:56:42+00:00 longevity-mini-test-ls-db-node-eastus-2 !    INFO |   File "/opt/scylladb/scylla-machine-image/libexec/scylla_post_start.py", line 57, in run_post_start_script
< t:2022-05-06 19:56:43,409 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-06T17:56:42+00:00 longevity-mini-test-ls-db-node-eastus-2 !    INFO |     post_start_script = self.instance_user_data.get("post_start_script")
< t:2022-05-06 19:56:43,409 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-06T17:56:42+00:00 longevity-mini-test-ls-db-node-eastus-2 !    INFO | AttributeError: 'NoneType' object has no attribute 'get'
< t:2022-05-06 19:56:43,409 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-06T17:56:42+00:00 longevity-mini-test-ls-db-node-eastus-2 !  NOTICE | scylla-image-post-start.service: Main process exited, code=exited, status=1/FAILURE
< t:2022-05-06 19:56:43,410 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-06T17:56:42+00:00 longevity-mini-test-ls-db-node-eastus-2 ! WARNING | scylla-image-post-start.service: Failed with result 'exit-code'.
< t:2022-05-06 19:56:43,410 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-06T17:56:42+00:00 longevity-mini-test-ls-db-node-eastus-2 !     ERR | Failed to start Scylla cloud image post start service.

```

For now I don't have details about precise versions (recent master) or more logs. Let me know if you need it.

**Comment by soyacz** [comment]
Yes I was passing user-data (in yaml format)

Sorry @benipeled I cannot reproduce it now. I'll get back when I have it again with some more logs/machine running. Maybe it was something wrong with my `user-data` as I'm developing some additional setup with it for testing purposes.

**Comment by fruch** [comment]
I think you can see that happening on both 5.0 and 2022.1 the azure AMI test keep failing there

**Comment by soyacz** [comment]
yes, I've forgot about this issue. It was already reported here: https://github.com/scylladb/scylla-pkg/issues/2879

**Comment by soyacz** [comment]
but on 5.0/2022.1 we don't pass `user-data`

**Comment by soyacz** [comment]
yup, this are not the same. @fruch did you spot user_data issue somewhere or the one I mentioned?

**Comment by fruch** [comment]
@benipeled  all  `azure_instance: *` commit @syuu1228 was doing are not in 5.0, 
this need to be clarified if azure image are needed for 5.0, if they do, lot of things need to be backported, if they don't, please remove the trigger for the azure image artifact job

**Comment by yaronkaikov** [comment]
@fruch AFAIK Azure is/should be part of 5.0, so if we have missing commits let's do the backports

**Comment by fruch** [comment]
> @fruch AFAIK Azure is/should be part of 5.0, so if we have missing commits let's do the backports

I don't know exactly what missing, but it should be test (and I don't have a bandwidth to do that now...)

**Comment by syuu1228** [comment]
I think we should backport at least this one:
[azure_instance: implement user-data](https://github.com/scylladb/scylla-machine-image/commit/37768f6b5d8ad40e26ef86a1db3fe03e56adc668)

And probably other bug fixes too:
[azure_instance: fix metadata url for location and zone](https://github.com/scylladb/scylla-machine-image/commit/f2745ab01c48d969c6a9dabec4e6a19762c53271)
[azure_instance: remove unneeded is_unsupported_instance_class()](https://github.com/scylladb/scylla-machine-image/commit/5b53ee3922f2f992d5f80d010a8b1cad6055e4b0)
[azure_instance: fix bromen is_recommended_instance_size()](https://github.com/scylladb/scylla-machine-image/commit/c7b90846532ea484ceeaa581fb773d2935c31ce2)
[azure_instance: support "swap disk"](https://github.com/scylladb/scylla-machine-image/commit/5d2c3eef957b0e9beff74ca1995cce86425fabdd)
[azure_instance: fix failing is_azure_instance()](https://github.com/scylladb/scylla-machine-image/commit/eba6b6585906c14765eee497a1ba70ea54a15d7a)

**Comment by yaronkaikov** [comment]
@syuu1228 please prepare the pr for 5.0,then we will merge from 5.0 to 2022.1

**Comment by syuu1228** [comment]
Sent PR: https://github.com/scylladb/scylla-machine-image/pull/355

**Comment by syuu1228** [comment]
We can close this now since the patchset merged
